[build]
  publish = "public"
  command = "echo SERVICE_ID=$SERVICE_ID >> .env.production && echo TEMPLATE_ID=$TEMPLATE_ID >> .env.production && echo USER_ID=$USER_ID >> .env.production && echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
